In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
import yaml
import math 
import glob

In [3]:
def get_part_of_image(origin_img,ori_gray): 
    edge1 = ori_gray[2744:3136,1824:2736]
    return edge1

origin_img = cv2.imread('/home/office5/Image_Code/Ketan_sir/data/Anna2.bmp')
ori_gray = cv2.cvtColor(origin_img,cv2.COLOR_BGR2GRAY)
cropped_gray_img = get_part_of_image(origin_img,ori_gray)
cv2.imwrite('gray.png',cropped_gray_img)

True

In [354]:
def get_point(path,points):
    for img1 in sorted(path):
        if img1 != '/home/office5/Image_Code/Ketan_sir/try_connected_component/0.png':
            img_name = img1.split('/')[-1]
            img = cv2.imread(img1)
            gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
            coords = np.column_stack(np.where(gray == 255))
            a = np.min(coords,axis=0)
            b = np.max(coords,axis=0)

            y_min,x_min,y_max,x_max = a[0],a[1],b[0],b[1]
            # print(a,b,y_min,x_min,y_max,x_max)

            i=0
            while(y_min >= coords[i][0] and x_min >= coords[i][1]):
                # print(img_name,coords[i])
                points.append(coords[i])
                i=i+1
                break

            i=0
            while(y_min >= coords[i][0] and x_max <= coords[i][1]):
                # print(img_name,coords[i])
                points.append(coords[i])
                i+=1
                break

            i=0
            while(y_max <= coords[i][0] and x_min >= coords[i][1]):
                # print(img_name,coords[i])
                points.append(coords[i])
                i+=1
                break

            i=0
            # print('Here')
            while(y_max <= coords[i][0] and x_max <= coords[i][1]):
                # points.append(coords[i])
                i+=1
                break
            # else:
            #     points.append(coords[-1])

    return points
    

path = glob.glob('/home/office5/Image_Code/Ketan_sir/try_connected_component/*.png')
points = []
extreme_points = get_point(path,points)


extreme_points = np.array(extreme_points)
copy_extreme_points = extreme_points.copy()
# print(extreme_points)

for i in range(len(extreme_points)):
    extreme_points[i] = extreme_points[i] + np.array([2744,1824])

b = []
for i in range(len(extreme_points)):
    # print(extreme_points[i][0])
    x1_s = extreme_points[i][1] - 4
    x2_s = extreme_points[i][1] + 5
    y1_s = extreme_points[i][0] - 4
    y2_s = extreme_points[i][0] + 5

    b.append([extreme_points[i],copy_extreme_points[i],ori_gray[y1_s:y2_s,x1_s:x2_s]])


In [7]:
def get_part_of_image(origin_img,ori_gray): 
    edge1 = ori_gray[2744:3136,1824:2736]
    return edge1

origin_img = cv2.imread('/home/office5/Image_Code/Ketan_sir/data/Anna2.bmp')
ori_gray = cv2.cvtColor(origin_img,cv2.COLOR_BGR2GRAY)
cropped_gray_img = get_part_of_image(origin_img,ori_gray)

CONFIG_PATH = "/home/office5/Image_Code/Ketan_sir"

def load_config(config_name):
    with open(os.path.join(CONFIG_PATH, config_name)) as file:
        config = yaml.safe_load(file)
    return config

config = load_config("config.yaml")

def get_index_kernel(arr2,def_arr):

    y1_s = arr2[0] + 2744 - config['top_left_point_kernel']
    y2_s = arr2[0] + 2744 + config['bottom_right_point_kernel']
    x1_s = arr2[1] + 1824 - config['top_left_point_kernel']
    x2_s = arr2[1] + 1824 + config['bottom_right_point_kernel']
    print(ori_gray)
    kernel_value =  ori_gray[y1_s:y2_s,x1_s:x2_s]
    print("kernel", kernel_value)
    count = 0
    for i in range(len(kernel_value[0])):
        for j in range(len(kernel_value[1])):
            # def_arr[i][j] = np.abs(np.subtract(int(kernel_value[4][4]),int(kernel_value[i][j])))
            def_arr[i][j] = (np.subtract(int(kernel_value[config['top_left_point_kernel']][config['top_left_point_kernel']]),int(kernel_value[i][j])))
            def_arr[config['top_left_point_kernel']][config['top_left_point_kernel']] = 5 
            if(def_arr[i][j]==0):
                def_arr[i][j] = 1
            elif(def_arr[i][j]<0):
                def_arr[i][j] = 0
            else:
                def_arr[i][j] = 1
            

    # if()
    return def_arr


curve_edge_point = [[210,197],[212,348],[290,602],[308,555],[206,741],[310,554],[211,274],[293,217],[376,513]]
sharp_edge_point = [[333,488],[262,728],[33,28],[51,526],[113,453],[246,582],[234,612],[371,463],[232,667],[327,413],[325,495],[25,530]]
curved_straight_point = [[45,417],[80,208],[31,459],[36,427],[40,911],[111,33],[70,737]]
a = np.load('coordinate.npy')
a = [tuple(row) for row in a]
a = np.unique(a,axis=0)

h = config['top_left_point_kernel'] + config['bottom_right_point_kernel']
# w = config['top_left_point_kernel'] + config['bottom_right_point_kernel']
def_arr = np.zeros((h,h))

print("all point testing Point")
for i in range(len(a)):
    # print(a[i])
    arr = np.array(a[i])
    def_arr = np.zeros((h,h))
    kernel_value = get_index_kernel(arr,def_arr)
    print(a[i][0],a[i][1])
    print(kernel_value)

# print("Curve edge Point")
# for i in range(len(curve_edge_point)):
#     print(curve_edge_point[i])
#     arr = np.array(curve_edge_point[i])
#     kernel_value = get_index_kernel(arr,def_arr)
#     print(kernel_value)
#     cropped_gray_img[curve_edge_point[i][0],curve_edge_point[i][1]]=255
#     # break

# print("Sharp point")
# for i in range(len(sharp_edge_point)):
#     print(sharp_edge_point[i])
#     arr = np.array(sharp_edge_point[i])
#     kernel_value = get_index_kernel(arr,def_arr)
#     cropped_gray_img[sharp_edge_point[i][0],sharp_edge_point[i][1]]=255
#     print(kernel_value)
#     # break

# print("curve straingh point")
# for i in range(len(curved_straight_point)):
#     print(curved_straight_point[i])
#     arr = np.array(curved_straight_point[i])
#     kernel_value = get_index_kernel(arr,def_arr)
#     print(kernel_value)
#     cropped_gray_img[curved_straight_point[i][0],curved_straight_point[i][1]]=255

# cv2.imwrite('point_on_image.png',cropped_gray_img)

all point testing Point
[[86 82 85 ... 95 94 96]
 [85 84 84 ... 96 95 94]
 [84 84 85 ... 96 94 94]
 ...
 [82 80 85 ... 96 93 96]
 [86 86 84 ... 99 95 92]
 [85 80 84 ... 95 95 95]]
kernel [[43 33 36]
 [74 58 47]
 [97 89 80]]
4 592
[[1. 1. 1.]
 [0. 5. 1.]
 [0. 0. 0.]]
[[86 82 85 ... 95 94 96]
 [85 84 84 ... 96 95 94]
 [84 84 85 ... 96 94 94]
 ...
 [82 80 85 ... 96 93 96]
 [86 86 84 ... 99 95 92]
 [85 80 84 ... 95 95 95]]
kernel [[10 14 17]
 [28 37 49]
 [65 74 79]]
9 534
[[1. 1. 1.]
 [1. 5. 0.]
 [0. 0. 0.]]
[[86 82 85 ... 95 94 96]
 [85 84 84 ... 96 95 94]
 [84 84 85 ... 96 94 94]
 ...
 [82 80 85 ... 96 93 96]
 [86 86 84 ... 99 95 92]
 [85 80 84 ... 95 95 95]]
kernel [[12 14 17]
 [26 37 50]
 [61 70 78]]
31 459
[[1. 1. 1.]
 [1. 5. 0.]
 [0. 0. 0.]]
[[86 82 85 ... 95 94 96]
 [85 84 84 ... 96 95 94]
 [84 84 85 ... 96 94 94]
 ...
 [82 80 85 ... 96 93 96]
 [86 86 84 ... 99 95 92]
 [85 80 84 ... 95 95 95]]
kernel [[26 30 61]
 [30 36 72]
 [56 60 80]]
33 28
[[1. 1. 0.]
 [1. 5. 0.]
 [0. 0. 0.]]
[[8

In [451]:
def get_part_of_image(origin_img,ori_gray): 
    edge1 = ori_gray[2744:3136,1824:2736]
    return edge1

origin_img = cv2.imread('/home/office5/Image_Code/Ketan_sir/data/Anna2.bmp')
ori_gray = cv2.cvtColor(origin_img,cv2.COLOR_BGR2GRAY)
cropped_gray_img = get_part_of_image(origin_img,ori_gray)

CONFIG_PATH = "/home/office5/Image_Code/Ketan_sir"

def load_config(config_name):
    with open(os.path.join(CONFIG_PATH, config_name)) as file:
        config = yaml.safe_load(file)
    return config

config = load_config("config.yaml")

def get_index_kernel(arr2,def_arr):

    y1_s = arr2[0] + 2744 - config['top_left_point_kernel']
    y2_s = arr2[0] + 2744 + config['bottom_right_point_kernel']
    x1_s = arr2[1] + 1824 - config['top_left_point_kernel']
    x2_s = arr2[1] + 1824 + config['bottom_right_point_kernel']

    kernel_value =  ori_gray[y1_s:y2_s,x1_s:x2_s]
    # print('kernel value')
    # print(kernel_value)
    count = 0
    for i in range(len(kernel_value[0])):
        for j in range(len(kernel_value[1])):
            # def_arr[i][j] = np.abs(np.subtract(int(kernel_value[4][4]),int(kernel_value[i][j])))
            def_arr[i][j] = (np.subtract(int(kernel_value[config['top_left_point_kernel']][config['top_left_point_kernel']]),int(kernel_value[i][j])))
            def_arr[config['top_left_point_kernel']][config['top_left_point_kernel']] = 5 
            if(def_arr[i][j]==0):
                def_arr[i][j] = 1
            elif(def_arr[i][j]<0):
                def_arr[i][j] = 0
                count+=1
            else:
                def_arr[i][j] = 1
            
    if(count==4):
        # pass
        return 1
        # print(arr2)
    else:
        # print(count)
    #     print('Not remove point')
        # print(def_arr)
        return 2


curve_edge_point = [[210,197],[212,348],[290,602],[308,555],[206,741],[310,554],[211,274],[293,217],[376,513]]
sharp_edge_point = [[333,488],[262,728],[33,28],[51,526],[113,453],[246,582],[234,612],[371,463],[232,667],[327,413],[325,495],[25,530]]
curved_straight_point = [[45,417],[80,208],[31,459],[36,427],[40,911],[111,33],[70,737]]

a = np.load('coordinate.npy')
a = [tuple(row) for row in a]
a = np.unique(a,axis=0)

h = config['top_left_point_kernel'] + config['bottom_right_point_kernel']
# w = config['top_left_point_kernel'] + config['bottom_right_point_kernel']
# def_arr = np.zeros((h,h))

print("all point testing Point")
for i in range(len(a)):
    # print(a[i])
    arr = np.array(a[i])
    def_arr = np.zeros((h,h))
    kernel_value = get_index_kernel(arr,def_arr)
    # print(kernel_value)
    if kernel_value != 1:
        print(a[i][0],a[i][1])
        cropped_gray_img[a[i][0],a[i][1]]=255

# print("Curve edge Point")
# for i in range(len(curve_edge_point)):
#     # print(curve_edge_point[i])
#     arr = np.array(curve_edge_point[i])
#     kernel_value = get_index_kernel(arr,def_arr)
#     # print(kernel_value)
#     cropped_gray_img[curve_edge_point[i][0],curve_edge_point[i][1]]=255
#     # break

# print("Sharp point")
# for i in range(len(sharp_edge_point)):
#     # print(sharp_edge_point[i])
#     arr = np.array(sharp_edge_point[i])
#     kernel_value = get_index_kernel(arr,def_arr)
#     cropped_gray_img[sharp_edge_point[i][0],sharp_edge_point[i][1]]=255
#     # print(kernel_value)
#     # break

# print("curve straingh point")
# for i in range(len(curved_straight_point)):
#     # print(curved_straight_point[i])
#     arr = np.array(curved_straight_point[i])
#     kernel_value = get_index_kernel(arr,def_arr)
#     # print(kernel_value)
#     cropped_gray_img[curved_straight_point[i][0],curved_straight_point[i][1]]=255

cv2.imwrite('removed_ExtremePoint.png',cropped_gray_img)

all point testing Point
33 28
112 454
113 453
231 728
231 735
232 667
232 668
233 738
234 612
237 218
237 636
238 742
240 240
262 612
262 728
262 735
265 671
269 358
274 586
283 719
283 761
285 495
285 544
286 380
286 381
286 413
287 212
287 298
287 320
291 548
292 453
308 533
309 553
310 554
330 523
332 436
333 488
344 549
369 509
370 509
370 531
371 400
375 535
375 574


True

True

In [436]:
a = np.load('coordinate.npy')
# print(a)
a = [tuple(row) for row in a]
# print(new_array)
a = np.unique(a,axis=0)
print(type(a))

<class 'numpy.ndarray'>


# only get corner 1 value extreme point

In [20]:

def get_part_of_image(origin_img,ori_gray): 
    edge1 = ori_gray[2744:3136,1824:2736]
    return edge1

origin_img = cv2.imread('/home/office5/Image_Code/Ketan_sir/data/Anna2.bmp')
ori_gray = cv2.cvtColor(origin_img,cv2.COLOR_BGR2GRAY)
cropped_gray_img = get_part_of_image(origin_img,ori_gray)

CONFIG_PATH = "/home/office5/Image_Code/Ketan_sir"

def load_config(config_name):
    with open(os.path.join(CONFIG_PATH, config_name)) as file:
        config = yaml.safe_load(file)
    return config

config = load_config("config.yaml")

def get_index_kernel(arr2,def_arr):

    y1_s = arr2[0] + 2744 - config['top_left_point_kernel']
    y2_s = arr2[0] + 2744 + config['bottom_right_point_kernel']
    x1_s = arr2[1] + 1824 - config['top_left_point_kernel']
    x2_s = arr2[1] + 1824 + config['bottom_right_point_kernel']

    kernel_value =  ori_gray[y1_s:y2_s,x1_s:x2_s]
    print(kernel_value)
    count = 0
    for i in range(len(kernel_value[0])):
        for j in range(len(kernel_value[1])):
            # def_arr[i][j] = np.abs(np.subtract(int(kernel_value[4][4]),int(kernel_value[i][j])))
            def_arr[i][j] = (np.subtract(int(kernel_value[config['top_left_point_kernel']][config['top_left_point_kernel']]),int(kernel_value[i][j])))
            def_arr[config['top_left_point_kernel']][config['top_left_point_kernel']] = 5 
            if(def_arr[i][j]==0):
                def_arr[i][j] = 1
            elif(def_arr[i][j]<0):
                def_arr[i][j] = 0
            else:
                def_arr[i][j] = 1
            

    # if()
    return def_arr

In [21]:
print("all point testing Point")
def get_extreme_point(a,dict1,extreme_point_list):
    for i in range(len(a)):
        arr = np.array(a[i])
        # print(arr)
        def_arr = np.zeros((h,h))
        kernel_value = get_index_kernel(arr,def_arr)
        unique_1_0 = np.unique(kernel_value,return_counts=True)
        # print(unique_1_0)
        count_0 = unique_1_0[1][0]
        count_1 = unique_1_0[1][1]
        # print(count_0,count_1)
        dict1['0'] = count_0
        dict1['1'] = count_1
        if (count_0==3 and count_1==5) or (count_0==5 and count_1==3):

            corner_1 = kernel_value[0][0]
            corner_2 = kernel_value[0][2]
            corner_3 = kernel_value[2][0]
            corner_4 = kernel_value[2][2]

            corner_point = np.array([corner_1,corner_2,corner_3,corner_4])
            for key, value in dict1.items():
                if value == 3:
                    corner_index = np.where(corner_point==int(key)) 

                    if corner_index[0][0] == 0:
                        x,y = 0,0
                        if (kernel_value[x][y]==int(key) and kernel_value[x+1][y]==int(key) and kernel_value[x][y+1]==int(key)):
                            extreme_point_list.append([a[i][0],a[i][1]])

                    if corner_index[0][0] == 1:
                        x,y = 0,2
                        if (kernel_value[x][y]==int(key) and kernel_value[x][y-1]==int(key) and kernel_value[x+1][y]==int(key)):
                            extreme_point_list.append([a[i][0],a[i][1]])

                    if corner_index[0][0] == 2:
                        x,y = 2,0
                        if (kernel_value[x][y]==int(key) and kernel_value[x-1][y]==int(key) and kernel_value[x][y+1]==int(key)):
                            extreme_point_list.append([a[i][0],a[i][1]])

                    if corner_index[0][0] == 3:
                        x,y = 2,2
                        if (kernel_value[x][y]==int(key) and kernel_value[x][y-1]==int(key) and kernel_value[x-1][y]==int(key)):
                            extreme_point_list.append([a[i][0],a[i][1]])


    return extreme_point_list

a = np.load('coordinate.npy')
a = [tuple(row) for row in a]
a = np.unique(a,axis=0)
h = config['top_left_point_kernel'] + config['bottom_right_point_kernel']

def_arr = np.zeros((h,h))
dict1 = {}
extrmem_point_list = []
value = get_extreme_point(a,dict1,extrmem_point_list)
print(value)
# cv2.imwrite('removed_ExtremePoint_2.png',cropped_gray_img)

all point testing Point
[[43 33 36]
 [74 58 47]
 [97 89 80]]
[[10 14 17]
 [28 37 49]
 [65 74 79]]
[[12 14 17]
 [26 37 50]
 [61 70 78]]
[[26 30 61]
 [30 36 72]
 [56 60 80]]
[[12 17 28]
 [31 47 63]
 [64 72 82]]
[[12 21 31]
 [40 52 64]
 [72 77 82]]
[[37 34 39]
 [45 53 66]
 [72 78 83]]
[[ 52  46  47]
 [ 82  61  44]
 [100  89  71]]
[[53 33 36]
 [74 41 24]
 [85 67 40]]
[[38 32 33]
 [65 49 40]
 [93 80 68]]
[[65 32 26]
 [84 50 26]
 [88 73 38]]
[[84 74 66]
 [82 66 46]
 [63 39 24]]
[[93 82 66]
 [87 63 39]
 [82 43 25]]
[[37 32 30]
 [60 47 36]
 [81 72 59]]
[[106 102  96]
 [ 84  72  60]
 [ 45  35  31]]
[[ 80  97 103]
 [ 42  53  74]
 [ 32  25  35]]
[[43 31 25]
 [80 68 51]
 [95 92 82]]
[[84 90 95]
 [52 64 78]
 [29 32 43]]
[[92 82 68]
 [73 57 40]
 [38 31 28]]
[[70 80 87]
 [36 47 60]
 [31 26 31]]
[[96 94 82]
 [76 62 47]
 [40 32 30]]
[[81 90 96]
 [45 63 84]
 [26 30 47]]
[[40 31 26]
 [71 61 46]
 [87 81 75]]
[[42 27 26]
 [78 60 38]
 [95 87 73]]
[[32 26 30]
 [68 47 28]
 [88 80 60]]
[[37 25 29]
 [70 51 30]


In [23]:
def_arr = np.zeros((3,3))
def_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [195]:
Anna2_img = "/home/office5/Image_Code/Ketan_sir/data/Anna2.bmp"
Anna2_img = cv2.imread(Anna2_img,0)

Anna3_img = "/home/office5/Image_Code/Ketan_sir/data/Anna19.bmp"
Anna3_img = cv2.imread(Anna3_img,0)


second_img_point = []
original_img_point = []
for i in range(len(value)):
    ori_img_loc_x = value[i][1] + 1824
    ori_img_loc_y = value[i][0] + 2744
    x1_f = ori_img_loc_x - 5
    x2_f = ori_img_loc_x + 5
    y1_f = ori_img_loc_y - 5
    y2_f = ori_img_loc_y + 5

    img_crop1  = Anna2_img[y1_f:y2_f,x1_f:x2_f]
    img_first = img_crop1.astype(np.int8)
    # print("Original",ori_img_loc_y,ori_img_loc_x)
    original_img_point.append([ori_img_loc_y,ori_img_loc_x])

    x1_s = ori_img_loc_x - 10
    x2_s = ori_img_loc_x + 10
    y1_s = ori_img_loc_y - 10
    y2_s = ori_img_loc_y + 10

    img_crop2  = Anna3_img[y1_s:y2_s,x1_s:x2_s]
    img_snd = img_crop2.astype(np.int8)

    dict1 = {}
    for i in range(10):
        for j in range(10):
            dict1[i,j] = np.mean(np.abs(img_first  - img_snd[i:i+10,j:j+10]))
    # print(dict1)
    i,j = min(dict1, key=dict1.get)

    # print(j,i)
    s_img_extr_point_x = x1_s + 10 - 5 + j # 10 for each block of first image and -5 for adding from width and height of first image
    s_img_extr_point_y =y1_s + 10 - 5 + i

    second_img_point.append([s_img_extr_point_y,s_img_extr_point_x])
    # print("From second image",s_img_extr_point_y,s_img_extr_point_x)

In [196]:
origin_img = cv2.imread('/home/office5/Image_Code/Ketan_sir/data/Anna2.bmp')
second_img = cv2.imread('/home/office5/Image_Code/Ketan_sir/data/Anna19.bmp')
edge1 = origin_img[2744:3136,1824:2736]
edge2 = second_img[2744:3136,1824:2736]

origin_img_point = original_img_point - np.array([2744,1824])
second_img_point = second_img_point - np.array([2744,1824])

for i in range(len(origin_img_point)):
    edge1[origin_img_point[i][0],origin_img_point[i][1]] = [255,255,255]

for i in range(len(second_img_point)):
    edge2[second_img_point[i][0],second_img_point[i][1]] = [255,255,255]

cv2.imwrite('orig_img_extr.png',edge1)
cv2.imwrite('snd_img_extr.png',edge2)

True

In [9]:
for i in range(len(value)):
    ori_img_loc_x = value[i][1] + 1824
    ori_img_loc_y = value[i][0] + 2744
    x1_f = ori_img_loc_x - 5
    x2_f = ori_img_loc_x + 5
    y1_f = ori_img_loc_y - 5
    y2_f = ori_img_loc_y + 5
    # print(y1_f,y2_f,x1_f,x2_f)

    Anna2_img = "/home/office5/Image_Code/Ketan_sir/data/Anna2.bmp"
    Anna2_img_c = cv2.imread(Anna2_img)
    Anna2_img_gray = cv2.imread(Anna2_img,0)
    img_crop1  = Anna2_img_gray[y1_f:y2_f,x1_f:x2_f]
    img_first = img_crop1.astype(np.int8)
    # plt.imshow(img_first)
    # plt.show()
    print("Original",ori_img_loc_y,ori_img_loc_x)
    Anna2_img_c[ori_img_loc_y][ori_img_loc_x] = [255,255,255]


    x1_s = ori_img_loc_x - 10
    x2_s = ori_img_loc_x + 10
    y1_s = ori_img_loc_y - 10
    y2_s = ori_img_loc_y + 10
    # print(y1_s,y2_s,x1_s,x2_s)

    Anna3_img = "/home/office5/Image_Code/Ketan_sir/data/Anna19.bmp"
    Anna3_img_c = cv2.imread(Anna3_img)
    Anna3_img_gray = cv2.imread(Anna3_img,0)

    img_crop2  = Anna3_img_gray[y1_s:y2_s,x1_s:x2_s]
    # plt.imshow(img_crop2)
    # plt.show()
    img_snd = img_crop2.astype(np.int8)

    dict1 = {}
    for i in range(10):
        for j in range(10):
            dict1[i,j] = np.mean(np.abs(img_first  - img_snd[i:i+10,j:j+10]))
    # print(dict1)
    i,j = min(dict1, key=dict1.get)

    print(j,i)
    s_img_extr_point_x = x1_s + 10 - 5 + j # 10 for each block of first image and -5 for adding from width and height of first image
    s_img_extr_point_y =y1_s + 10 - 5 + i

    Anna3_img_c[s_img_extr_point_y][s_img_extr_point_x] = [0,0,255]
    print("From second image",s_img_extr_point_y,s_img_extr_point_x)

cv2.imwrite('Original_image_anna2.png',Anna2_img_c)
cv2.imwrite('Second_image_anna3.png',Anna3_img_c)

In [140]:
a = np.load('coordinate.npy')
a = [tuple(row) for row in a]
a = np.unique(a,axis=0)

h = config['top_left_point_kernel'] + config['bottom_right_point_kernel']
# w = config['top_left_point_kernel'] + config['bottom_right_point_kernel']
def_arr = np.zeros((h,h))


m= 0
dict1 = {}
print("all point testing Point")
for i in range(len(a)):
    arr = np.array(a[i])
    def_arr = np.zeros((h,h))
    kernel_value = get_index_kernel(arr,def_arr)
    unique_1_0 = np.unique(kernel_value,return_counts=True)
    count_0 = unique_1_0[1][0]
    count_1 = unique_1_0[1][1]
    dict1['0'] = count_0
    dict1['1'] = count_1
    min_3_5 = np.minimum(count_0,count_1)
    if (count_0==3 and count_1==5) or (count_0==5 and count_1==3):

        corner_1 = kernel_value[0][0]
        corner_2 = kernel_value[0][2]
        corner_3 = kernel_value[2][0]
        corner_4 = kernel_value[2][2]
        # print(corner_1,corner_2,corner_3,corner_4)
        corner_point = np.array([corner_1,corner_2,corner_3,corner_4])
        # print(corner_point)
        for key, value in dict1.items():
            if value == 3:
                corner_index = np.where(corner_point==int(key)) 

                if corner_index[0][0] == 0:
                    x,y = 0,0
                    if (kernel_value[x][y]==int(key) and kernel_value[x+1][y]==int(key) and kernel_value[x][y+1]==int(key)):
                        print(a[i][0],a[i][1])
                        print(kernel_value)
                        cropped_gray_img[a[i][0],a[i][1]]=255

                        print('3*3 --> 0')
                        m+=1

                if corner_index[0][0] == 1:
                    x,y = 0,2
                    if (kernel_value[x][y]==int(key) and kernel_value[x][y-1]==int(key) and kernel_value[x+1][y]==int(key)):
                        print(a[i][0],a[i][1])
                        print(kernel_value)
                        cropped_gray_img[a[i][0],a[i][1]]=255

                        print('3*3 --> 1')
                        m+=1

                if corner_index[0][0] == 2:
                    x,y = 2,0
                    if (kernel_value[x][y]==int(key) and kernel_value[x-1][y]==int(key) and kernel_value[x][y+1]==int(key)):
                        # pass
                        print(a[i][0],a[i][1])
                        print(kernel_value)
                        cropped_gray_img[a[i][0],a[i][1]]=255
                        print('3*3 --> 2')
                        m+=1

                if corner_index[0][0] == 3:
                    x,y = 2,2
                    if (kernel_value[x][y]==int(key) and kernel_value[x][y-1]==int(key) and kernel_value[x-1][y]==int(key)):
                        print(a[i][0],a[i][1])
                        print(kernel_value)
                        cropped_gray_img[a[i][0],a[i][1]]=255
                        print("3*3 --> 3")
                        m+=1
print(m)
cv2.imwrite('removed_ExtremePoint_2.png',cropped_gray_img)

all point testing Point
33 28
[[1. 1. 0.]
 [1. 5. 0.]
 [0. 0. 0.]]
3*3 --> 0
112 454
[[0. 0. 1.]
 [0. 5. 1.]
 [1. 1. 1.]]
3*3 --> 0
113 453
[[0. 0. 0.]
 [0. 5. 1.]
 [0. 1. 1.]]
3*3 --> 3
231 728
[[1. 0. 0.]
 [1. 5. 0.]
 [1. 1. 1.]]
3*3 --> 1
231 735
[[0. 0. 1.]
 [0. 5. 1.]
 [1. 1. 1.]]
3*3 --> 0
232 667
[[0. 0. 0.]
 [0. 5. 1.]
 [0. 1. 1.]]
3*3 --> 3
232 668
[[0. 0. 0.]
 [0. 5. 1.]
 [0. 1. 1.]]
3*3 --> 3
233 738
[[1. 1. 0.]
 [1. 5. 0.]
 [0. 0. 0.]]
3*3 --> 0
234 612
[[0. 0. 0.]
 [0. 5. 1.]
 [0. 1. 1.]]
3*3 --> 3
237 218
[[0. 0. 0.]
 [0. 5. 1.]
 [0. 1. 1.]]
3*3 --> 3
237 636
[[1. 1. 1.]
 [0. 5. 1.]
 [0. 0. 1.]]
3*3 --> 2
238 742
[[0. 0. 1.]
 [0. 5. 1.]
 [1. 1. 1.]]
3*3 --> 0
240 240
[[1. 1. 0.]
 [1. 5. 0.]
 [0. 0. 0.]]
3*3 --> 0
262 612
[[0. 0. 0.]
 [0. 5. 1.]
 [0. 1. 1.]]
3*3 --> 3
262 728
[[1. 1. 1.]
 [1. 5. 0.]
 [1. 0. 0.]]
3*3 --> 3
262 735
[[1. 1. 1.]
 [0. 5. 1.]
 [0. 0. 1.]]
3*3 --> 2
265 671
[[1. 1. 0.]
 [1. 5. 0.]
 [0. 0. 0.]]
3*3 --> 0
283 761
[[1. 1. 0.]
 [1. 5. 0.]
 [0. 0. 0.]

True

In [2]:
import numpy as np
a = np.load('coordinate.npy')
print(a)

[[112 454]
 [ 51 526]
 [ 51 526]
 [ 31 459]
 [  4 592]
 [ 33  28]
 [ 33  28]
 [113 453]
 [  9 534]
 [ 88 248]
 [123  21]
 [ 56 395]
 [ 45 417]
 [ 46 415]
 [290 763]
 [292 478]
 [333 488]
 [344 549]
 [294 195]
 [207 716]
 [212 348]
 [377 496]
 [211 274]
 [344 549]
 [344 549]
 [233 738]
 [233 738]
 [285 495]
 [ 71 247]
 [262 735]
 [262 735]
 [262 728]
 [291 747]
 [286 413]
 [375 534]
 [292 361]
 [286 381]
 [286 413]
 [376 465]
 [262 612]
 [265 671]
 [262 612]
 [265 671]
 [292 453]
 [209 301]
 [294 252]
 [286 191]
 [294 215]
 [308 555]
 [255 353]
 [269 358]
 [287 688]
 [286 380]
 [378 388]
 [223 399]
 [243 408]
 [307 554]
 [336 570]
 [292 764]
 [291 548]
 [292 565]
 [295 197]
 [285 544]
 [308 533]
 [310 554]
 [375 574]
 [232 667]
 [246 695]
 [293 480]
 [370 531]
 [369 509]
 [205 596]
 [292 529]
 [370 509]
 [370 509]
 [274 586]
 [376 499]
 [376 512]
 [332 436]
 [309 553]
 [375 573]
 [208 345]
 [287 212]
 [231 735]
 [231 728]
 [231 735]
 [375 512]
 [206 527]
 [210 349]
 [371 400]
 [290 708]